### ISSUE TITLE
Requested UI changes

### ISSUE THREAD

**Issue by coleslaw481** [BrettJSettle/NBGWAS-Frontend#6]
![changes_to_nagaui](https://user-images.githubusercontent.com/655940/50036751-3d2d9000-ffc0-11e8-9fbe-c61d37a51906.png)

**Comment by coleslaw481** [comment]
The pregenerated json can be found here: http://nbgwas.ucsd.edu/nagadata/example_output/example_schizophrenia_output.json

**Comment by BrettJSettle** [comment]
This is fantastically cleaner. Will make the changes ASAP. Thanks!

**Comment by coleslaw481** [comment]
Crap, I missed one other thing to add. Dexter wanted this text added as well:

 **NOTE:** This service is experimental. The interface is subject to change.
 
 See https://github.com/shfong/nbgwas for details and to report issues.

**Comment by BrettJSettle** [comment]
First pass up for review

**Comment by coleslaw481** [comment]
This looks great. thanks.
